### ISSUE TITLE
seems to be broken

### ISSUE THREAD

**Issue by mothmoss** [Mwr247/DnDBeyondSpellPoints#1]
as of 4/2/2022
tested on two devices broken on both - unless i'm the clown, somehow

**Comment by Xneose** [comment]
Also having issues with the extension. The whole thing seems to not function. I've only tested it on chrome so I'm not sure about firefox.

**Comment by Mwr247** [comment]
Appreciate the heads up @mothmoss and @Xneose . I've been out of town until recently so I hadn't checked this, but I'm seeing it as broken as well. I actually use a mostly rewritten test version myself for personal use, and even that's broken, so I think they changed up something on the selectors. I'll see if I can find and push a fix =)

**Comment by Mwr247** [comment]
@mothmoss @Xneose The aforementioned issues should be fixed in version 1.1. Or at least, they are in FireFox for me. I'm not able to test in Chrome at the moment, but let me know if you encounter any issues and I can investigate further.
