### ISSUE TITLE
Level rounding is off for half casters

### ISSUE THREAD

**Issue by abpwem** [Mwr247/DnDBeyondSpellPoints#2]
Hey! First of all, thanks for the script!

I've noticed the rounding point for half casters is off on odd levels. This really shows at levels 3, 5, 7. Easy fix.

Line 69 is the issue. Can be fixed with the following.

player.level = Math.ceil(caster.reduce((lvl, val) => lvl + ((val.split(' ')[1] * (1 - 0.5 * /Artificer|Paladin|Ranger/.test(val)))), 0));

Thanks again for the script friend, it's great!

**Comment by Mwr247** [comment]
Oh no, someone's reading my horrible code XD

Good catch though, and thanks for making it easier by sharing the fix you made. I'll push it here soon =)
